import { BaseEntity } from './../../shared';

export class SurveyQuestion implements BaseEntity {
    constructor(
        public id?: number,
        public targetId?: string,
        public targetName?: string,
        public surveyCode?: string,
        public subSeq?: string,
        public report?: string,
        public reportTime?: string,
        public questionSummary?: string,
        public questionType?: string,
        public questionInfo?: string,
        public deptPlan?: string,
        public deptPlanType?: string,
        public deptPlanExtra?: string,
        public questionStatus?: string,
        public masterDeptId?: string,
        public auxDeptId?: string,
        public officePlan?: string,
        public officePlanJson?: string,
        public officeSubmitUuid?: string,
        public officeSubmitTime?: string,
        public leaderConfirm?: string,
        public leaderConfirmTime?: string,
        public leaderRemarks?: string,
        public leaderSubmitUuid?: string,
        public leaderSubmitTime?: string,
        public rstProcedure?: string,
        public rstOutcome?: string,
        public rstDate?: string,
        public rstTarget?: string,
        public flowStatus?: string,
        public inputDeptId?: string,
        public inputUser?: string,
        public inputPhone?: string,
        public inputTime?: string,
        public surveyId?: number,
        public onsiteId?: number,
        public departmentId?: number,
    ) {
    }
}
